### ISSUE TITLE
`pretext build -o` help clarification

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#104]

**Comment by oscarlevin** [comment]
This originated because a user was surprised that `-o output/html` put another html folder inside `output\html`.  Now that doesn't happen (I think).  Should it?  That is, should the files produced by the conversion be put in the <target> subfolder of the folder specified by -o?  

Either way, I think the help text could still be improved for the -o option, but I'm not sure about the right way to say it.  "Location of produced files"?

**Comment by StevenClontz** [comment]
Yeah, I think the current pattern is to explicitly set `output/html` for an `html` build, since you might actually have multiple `html` builds (`output/html`, `output/html-instructor`, etc.).

**Comment by StevenClontz** [comment]
I think this is closed by 0cd0ba3, please confirm.
