### ISSUE TITLE
Allow in-place HTML builds for large projects

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#162]
I just built DMOI using the CLI (yay!) and noticed that it takes a minute or two on the step to copy the output from the temp directory to output.  Not surprising, as there 6,372 files that must be copied.  

Should we allow a user to build directly into output (as a subfolder of the project, to avoid the --clean deleting important files issue) to save a little time?  

Not sure what that would mean for the custom xsl.  I suppose that could still be put in a temp directory.

**Comment by StevenClontz** [comment]
Can you hack that in and see how much time is saved in practice? Naively, I
wonder if building to the temporary directory isn't much additional time
lost, since the copying is (I believe, maybe depending on the system)
taking files stored in RAM and writing them to disk for the first time.


Steven Clontz
https://clontz.org - ***@***.***

**Comment by oscarlevin** [comment]
I think this is not worth pursuing
