### ISSUE TITLE
clean up template book xmlids/filenames

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#179]
I think it's a little confusing that we have the file `ch_first-chatper.ptx` with the xml:id `ch-first`. I think both should be renamed to the same thing, and either only hyphens or only underscores should be used. Similar issues throughout should be audited.

Optional: actually I'd like to model using folders to organize content for each chapter (`ch1/main.ptx`, `ch1/sec1-1.ptx`, etc.), but that's more of a personal preference perhaps. @oscarlevin please weigh in.

**Comment by oscarlevin** [comment]
There might be some benefit to showing that the file name and the xml:id need not be the same, but I agree we could be more consistent.

As for subfolders, I much prefer having all main files in the same folder, maybe with folders for particular types of things (like worksheets, exercises, etc).  Two reasons: 1, that is what @davidfarmer produces when he converts a book, and 2, if you decide that the section on recurrence relations should go in the chapter on sequences instead of the chapter on induction, you don't need to move files around *and* change paths in your xincludes.

**Comment by StevenClontz** [comment]
Is there a reason to have the filenames and xml:ids be inconsistent? That seems like an antipattern we shouldn't encourage to me, but maybe there's a usecase I'm not thinking of.

I like structuring things with more folders, but our basic book isn't too complicated anyway so there's no hard need for it. (I seemed to recall that was your take on it as well.) Maybe one folder as an example to show it can be done wouldn't hurt, perhaps for a few exercises as you suggest.

**Comment by rbeezer** [comment]
My $0.02 worth.  Expressing a project's document structure with a hierarchcy of directories/folders is duplicitous and just gets in the way.  ;-) The XML is one monolithic tree and contains all of this information, which is easy to mine/manipulate.  Once you read in all the files (via `xi:include`) the majority of file system structure is gone.

But perhaps you want to turn `@xml:id` back into files?  Or there is something else about the CLI I'm not considering.

**Comment by StevenClontz** [comment]
I went with the model of `prefix_whatever-the-slug-is`, for example, `sec_first-second`, and any file's root element has a matching id (other than main.ptx). I strongly encourage authors to match filesnames to the xml:id of their root element to help finding where things live in source as they author, so we should model that behavior ourselves.
