### ISSUE TITLE
Install PreTeXt resources to user directory

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#180]
The more I learn about how Python/PyPI distributes files ("resources") in packages, the more I worry about our brittle handling of static files. I think the more Pythonic solution is to ship a ZIP of the XSL files, install them to `~/.pretext/` or similar, and use them from there.

The problem with our current solution is that we try to grab a filepath to XSL assuming resources exist on disk, but it's feasible that a user might install the package as a zip, so the file doesn't actually exist. XSL cannot work together unless they actually live on the disk in the expected relative paths, so we need to put them on disk somewhere.

**Comment by oscarlevin** [comment]
Given discussion about epub (https://github.com/PreTeXtBook/pretext/issues/1778), I think it is time to move on this.  I'd be happy to work on it this week to get epub working.

I'm actually surprised that epub is half-working at all, since I don't understand how we are telling core where the scripts folder is, even when it is put in static.  Should be a fun puzzle.

**Comment by StevenClontz** [comment]
I'm on vacation this week so you have free reign here. I had this pattern in mind:

- need to do something
- check to see if resources are installed to user directory
- if not, install them
- do the thing with installed resources

We'll need to have a mechanism to mock this installation for testing purposes. 

Maybe we can/should have a `--local` flag on main command that says to install/use from a `.ptx` subdirectory of the project?
