### ISSUE TITLE
Improve python version management

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#224]
Not sure what to call this since I'm not sure what exactly the issue is, but we have had a fair number of support requests resulting from issues with the python install, rather than the cli.  For example, Tom J was unable to upgrade beyond 0.2 because he had a slightly older version of python.  Ben A. has had trouble with pdfcropmargins, likely because he has multiple pythons installed (guessing).  I've run into a similar issue.

So perhaps we can test for the python version and the cli version on each run, report in debug mode, or warn if seriously out of date.  In debug, we could give the path to the python using to run the cli.

**Comment by StevenClontz** [comment]
`pdfcropmargins` is an easier fix: we should update core scripts to use it as a library (a current feature that wasn't available originally), rather than calling the commandline.

Of course any change we make to the CLI won't help those using older versions. We already report CLI/Python info with `pretext support`, so if we're asking/requiring users to post that info, we'll quickly diagnose issues with e.g. Python 3.8.4 users getting 0.2.

**Comment by bnmnetp** [comment]
I was surprised when I looked at the Pipfile and saw `python_version = "3.8.5"` My understanding is that it will want exactly 3.8.5 instead of >= 3.8.5.  The latest in the 3.8 series is 3.8.13 Much less that the latest official version of Python is 3.10.4.  Requiring an exact version of python seems like it is going to cause a lot of frustration.

I would recommend trying to loosen that restriction to allow for all pythons >= 3.8.5

**Comment by StevenClontz** [comment]
See https://github.com/PreTeXtBook/pretext-cli/issues/182 - I expect to move away from pipenv at some point.

https://github.com/PreTeXtBook/pretext-cli/blob/main/Pipfile is what we're developing with. But https://github.com/PreTeXtBook/pretext-cli/blob/main/setup.py is what's used for packaging, and I believe we're correctly setting the *minimum* Python to be 3.8.5 as can be seen at https://pypi.org/project/pretextbook/

**Comment by bnmnetp** [comment]
Yep, I can see that.  But doing a `pipenv sync` wants to install exactly 3.8.5 for me.  I just changed the Pipfile to read 3.10 so it will accept any 3.10.x on my machine.

I don't mean to create noise.  I'm just experimenting to see if I can use ONE build tool, but still keep up with the HEAD of pretext core development.

**Comment by StevenClontz** [comment]
Gotcha. My (naive?) motivation is that since this is a dev tool, it needs to target the lowest Python we support, so devs don't accidentally introduce functionality that requires a later Python. I use pyenv to have a dedicated Python for CLI development.

Also it seems pipenv doesn't support \geq versions: https://stackoverflow.com/questions/51492423/pipenv-specify-minimum-version-of-python-in-pipfile

We'll revisit once classes end in a couple weeks...

**Comment by bnmnetp** [comment]
I just banged my head against this problem today...  I tried to add the pretext cli to my pyproject.toml file for the runestone server and poetry failed to solve dependencies because I am running Python 3.9.12

I can work around it for development purposes with a manual `pip install pretextbook` But thats not good for when I create new Docker containers to update my servers...

For whatever reason it seems Pipenv maintainers are not willing to allow  python_version = "> 3.8" or whatever.

My suggestion would be to take out the section of your Pipfile:
```
[requires]
python_version = "3.8.5"
```
This will allow developers to use any version of Python.  In your setup.py file you can set a python_requires=">=3.8" if you want to keep *users* from doing dumb stuff.  Developers should be more resilient and able to deal with multiple python versions.

**Comment by StevenClontz** [comment]
I think the best solution is to switch to poetry to ensure we're cross-compatible with Runestone's poetry setup. But I went ahead and dropped the python requirement in cb653e6

**Comment by StevenClontz** [comment]
closed as of https://github.com/PreTeXtBook/pretext-cli/commit/c3996a68128936c04a5764339584b1068f9af8be
