### ISSUE TITLE
`pdf-crop-margins` sometimes fails

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#240]
On WSL, both the pip installed and the pipenv development shell fail to build images because pdf-crop-margins doesn't work.   Outside of the pipenv shell, if I run `python -m pdf-crop-margins` I'm told there is no module with that name.  Inside the shell, I get 

    Error in pdfCropMargins: No system PyPDF2 Python package
    was found.  Reinstall pdfCropMargins via pip or install that
    dependency ('pip install pypdf2').

But in either case, doing a `pip install pdfCropMargins` or `pip install pypdf2` says the requirements are already satisfied.

This is surely related to issues raised on [pretext-support recently](https://groups.google.com/g/pretext-support/c/bHNg69j_mCo)

**Comment by StevenClontz** [comment]
When we look at this, we should also consider the programmatic interface described at https://github.com/abarker/pdfCropMargins/issues/20 and make a PR in PreTeXtBook/pretext to use the it rather than a subprocess.

Leaving this open here as it's a dependency issue and PreTeXtBook/pretext doesn't do dependency management (otherwise I think it's completely on that side).

**Comment by StevenClontz** [comment]
Eyeballing https://github.com/abarker/pdfCropMargins/issues/36 maybe this is solved upstream in https://github.com/py-pdf/PyPDF2/issues/779

**Comment by StevenClontz** [comment]
This was fixed at some point last week
