### ISSUE TITLE
`pretext generate ...`: what goes in the blank?

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#254]
Currently `pretext generate` expects a `target` argument, so you would type something like `pretext generate latex` which would generate all elements for the target "latex".  But I want to be able to type `pretext generate webwork` which would generate webwork for all targets.  For most asset elements, the only thing you would generate would be for their typical target (latex-image only generates things for html, for example).  

Proposal: `pretext generate sageplot` generates all sageplot formats for all formats in project.ptx.  You can limit things with optional commands, like `pretext generate sageplot -t latex -f png`.

**Comment by StevenClontz** [comment]
Something to ask a bunch of authors next week! But I'll need some strong arm-twisting to move away from the pattern we currently have: if a subcommand (that refers to an existing project) has an argument, that argument always refers to a target of that project.

Maybe what this reveals to me is that our default targets are misnamed. Instead of `pretext build html`, maybe it should be `pretext build web`, and instead of `pretext build pdf` it should be `pretext build print`. Then `pretext generate web` is short for "pretext generate [assets for] web". If you want, I think then `pretext generate --asset=webwork web` would be valid.

Actually if you're okay with it, I may have convinced myself to slip in a PR for 0.7 I'll link shortly..

**Comment by StevenClontz** [comment]
https://github.com/PreTeXtBook/pretext-cli/pull/255

**Comment by StevenClontz** [comment]
See work in 1f02abbed6a33aa95e72bba88b5cc776d0f6c2a3 - we now have a fairly consistent pattern where you can `pretext generate`, or `pretext build -g` (== `pretext generate && pretext build`), or `pretext view -gb` (== `pretext generate && pretext build && pretext view`). Likewise, if you just want webwork, you can run `pretext generate -a webwork` or `pretext build -ga webwork` (didn't implement in view but maybe I should). In particular, folks who are generating are also building and viewing - with the current design there are no surprises in which options go where based on the subcommand.

**Comment by StevenClontz** [comment]
I was convinced this week to support `pretext generate ASSET_TYPE`.
