### ISSUE TITLE
Use continuous integration for packaging

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#33]
I just screwed up following VERSIONING.md already. (-: Which made me think of the following:

Ideally, I'd like to have testing and packaging handled via continuous integration like https://travis-ci.org/ or https://circleci.com/. This has nice advantages such as being able to tell if pull requests pass our tests without having to pull them locally. And if I understand correctly, we can rig things so that once we complete a milestone in our issues, the CI solution can automatically build and publish the appropriate release to PyPI.

**Comment by StevenClontz** [comment]
https://github.com/marketplace/actions/pypi-publish looks like a slick way to publish to PyPI

**Comment by StevenClontz** [comment]
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by StevenClontz** [comment]
GitHub Actions now runs tests - need to research how to build from GitHub.

**Comment by oscarlevin** [comment]
I am now building and publishing releases for nightly builds.  It would be easy to write an action that does all this on some trigger for complete builds, like tagging a release.

Or are we satisfied with the `release_stable.py` script workflow?  What say you @StevenClontz?

**Comment by oscarlevin** [comment]
There is now a deploy-patch workflow that must be triggered manually.  But this could be changed to be triggered upon a push of a new tag.  And it could then also create a release (I think).  Or it could be triggered by the creation of a release.  We could do similar things for minor and major releases.

The only issue right now is that part of the action is to bump the version so that new nightly releases have the correct forward looking version.  But that requires committing and pushing.  Github is rejecting this push since we have a restriction that things must pass a test first.  Should we turn this restriction off?  I'm not sure how much we respect it anyway (seems only to matter on pull requests; I can push to main without any warning).

**Comment by oscarlevin** [comment]
I think this is working well enough to close this.  We could try to integrate the tagging of a new release automatically, but that can come later.
