### ISSUE TITLE
Update core script to provide local support for generating interactive screenshots

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#332]
In today's drop-in, Rob agreed to help with an XSL sheet that creates an HTML page with all the interactives for a book, if I'd write the core Python routine to slurp this up with Pyppeteer and produce our screenshots. So I think we can have that done next week, and include it with a 1.0 release. (Hence me also adding another 1.0 issue for @oscarlevin to look at before we deploy.)

**Comment by rbeezer** [comment]
Nothing is as easy as you would think,

Interactives are built as `iframe` - always, as a form of sandboxing, so all of these pages must be built, since a page of **just** interactive is going to reference them.  Then they rely on various "external" assets: JS libraries, JS scripts, iframe from other places, etc.  So that all needs to be placed in the right (relative) location.  I've got all this sorted.

Two interactives that behave in the sample article are not rendering on the page I built.  One is the Sage interact for Riemann sums, the other is the D3 visualization  of Welsh Assembly tweet mentions.  A few others are broken in both places.  I can't see what is wrong with the two problem examples.

`interactive` is not "official" yet, since they are so much trouble and still suspect.  I'm not really inclined to go backwards in a rush for 1.0.  Thoughts?

I can beat on this some more later, and post a beta version for folks to test.

**Comment by rbeezer** [comment]
Sage interact seems better when hosted on a server (not viewed locally).

Welsh Assembly tweets succeeds at website since some old directories are there, when a JS file actually needs an edit.

Broken `three.js` example seems to be missing example files at their website.

Wolfram CDF slated for removal very soon.

By no  means final, but perhaps useful for testing the necessary Python.

https://pretextbook.org/beta/2022-08-06-interactive/interactives.html

**Comment by StevenClontz** [comment]
I'm okay punting this to a later release. Class planning has me slammed and I'm not free to do much for a few weeks that isn't quick and simple.

The sage thing makes me think the `file://` protocol isn't a viable solution and we'll need to spin up a localhost, not too hard in Python. Still could have some issues - dunno how an `https` iframe behaves with an `http` localhost.

**Comment by rbeezer** [comment]
Got distracted by all the fix-ups needed by the various complexities of `interactive`.  In much better shape now.

Added a **preliminary** stylesheet to produce a page of interactives.  Tested with sample article.  It needs a filter so that if an author provides a `@preview` then it does not take a snapshot.

*  Stylesheet is `xsl/pretext-interactives.xsl`.  I may rename it to `extract-interactives.xsl` once we finalize.  I can take care of that.
*  Produced page is called `interactives-needing-snapshotting.html` which I hope is odd enough to prevent conflicts/overwrites.
*  Needs all supporting files from `external` to be in place.
*  I'd suggest sending `xsltproc()` output to a temporary directory and working there.
*  You could count the number of `iframe` on the page and set the delay to some fixed amount, plus a multiple of the number of interactives?

**Comment by oscarlevin** [comment]
I think this is done now, using playwright.
