### ISSUE TITLE
Versioning and release policy; requirements.txt

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#343]
In response to an error posted on pretext-support, I did a bug-fix that should be released as 1.0.2.  This got me thinking about whether it makes sense to adopt the following policy:

- If we fix a minor error with the CLI, we version +0.+0.+1, but in particular, do NOT update the core commit.
- If we add a new feature or any time we update the core commit, we version +0.+1.0.

This way, we can relax the check for requirements.txt to only check up to the first decimal point.  Patches should never result in previously built things no longer being able to be built (or get built differently).

Thoughts?

**Comment by bnmnetp** [comment]
I've been thinking about cli related release issues as well.

What about the case where I have fixed some important runestone javascript bugs.  To get this out to the world.  We need to update `xsl/support/runestone-services.xml` so that the build will know where to find the new versions of the javascript files.  `https://runestone.academy/cdn/runestone/x.y.z`

I guess that technically means updating the core to get that.

The example that triggered all of this was the changes I made to support display math in parsons problems, and to fix some timing problems with MathJax in multiple choice and matching.

**Comment by oscarlevin** [comment]
Upon further discussion, here is our policy moving forward.

Any quick update to either the CLI or the core commit, that doesn't add a new "feature" will increase the patch number (+0.+0.+1).  An update that adds a feature, or requires changing the CLI logic to fix a failed test due to a core commit update, will get a minor update (+0.+1.0).

**Comment by rbeezer** [comment]
Late to the party, and mostly for Brad/Runestone.

> What about the case where I have fixed some important runestone javascript bugs.

I believe David F only increments PTX JS when there are backward-incompatible changes.  In other words, HTML and JS evolve and so long as changes are fixes, additions, improvements, then there is no release, no new version number.

So he and I only coordinate, ala RS services file, once in a while.  I realize that may be unsettling to some (all?) on this thread.  ;-)

**Comment by bnmnetp** [comment]
That is my strategy as well based on semver.

1. I only update major version for breaking API or new architecture
2. I update the minor version with a new API
3. I update the subminor version with bug fixes or changes that do not change the API

**Comment by StevenClontz** [comment]
This is our goal but without semantic versioning of core PreTeXt (or more
coordination with core development) we really just have an approximation.
