### ISSUE TITLE
provision projects identically for build and generate

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#390]
See https://groups.google.com/g/pretext-dev/c/5FK6ip72Bwc/m/tKeWEm-KAgAJ

It seems custom XSL is not being copied for a generate action, which may be unintentional.

**Comment by oscarlevin** [comment]
This turns out to be more complicated than I thought it would be.  The core build command all have an `extra_xsl` argument that we exploit to point to the temporary directory of the copied xsl specified in the `project.ptx` file.  But none of the generate core routines have this argument, so they will always use the version given by `set_ptx_path(resources.path())`.

Is there a reason that someone would use custom xsl to build any assets?  I know we are trying to support development of the xsl, and thought this might be a clever way to get that for free.  Perhaps what we really need is a (hidden?) option that specifies the location of `ptx_path`.

**Comment by Alex-Jordan** [comment]
In my developer role, I was looking for this ability. Primarily (but not exclusively) to use a version of `extract-pg.xsl` that is under development to generate webwork assets.

In theory I can think of situations where an author/publisher would want this. Very rare in practice, I imagine. Except it is happening right now with the Active Calculus team, so that Chrissy can use a bleeding edge version with Runestone.

**Comment by StevenClontz** [comment]
Hm. I was going to suggest https://github.com/PreTeXtBook/pretext-cli#development 

However, I think AC needs to be using the version of the CLI Runestone uses I believe, since Runestone does its own build on its end.

I think this is worth doing as handling source (which includes custom XSL) differently in different contexts for the same target will inevitibly cause surprises like this.

**Comment by Alex-Jordan** [comment]
What I was referring to is a special side project version of AC that only Chrissy's course will use for now. Mitch, Brad, Chrissy, Matt, and I have things ironed out for that, for now. Not using the CLI for building WW representations. But we would if this happens.

**Comment by oscarlevin** [comment]
I am pretty sure this issue is no longer relevant since 2.0 was released.  Please reopen if this is incorrect.
