### ISSUE TITLE
refactor/legacy custom build bugs

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#483]
See https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/2023-slides/slides/build.py for some workarounds I'm hacking in to deal with some bugs we need to iron out.

- A legacy `<project/>` should have defaults like `project.source = Path("")` not `project.source = Path("source")`.
- In https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/build.py#L59 I naively thought `is_file` would guess if a path would be a file (e.g. does it have a period). But instead it's returning `False` when the file doesn't exist. This needs to be smarter.

**Comment by bjones1** [comment]
> * A legacy `<project/>` should have defaults like `project.source = Path("")` not `project.source = Path("source")`.

Fixed in #486.

**Comment by bjones1** [comment]
@StevenClontz, @oscarlevin and I chatted about the code you mentioned from https://github.com/PreTeXtBook/pretext-cli/blob/main/pretext/build.py#L59:

``` Python
            if output.is_file():
                output_filename = output.name
                output = output.parent
            else:
                output_filename = None
```

There's similar code in the refactored project:

``` Python
    def output_dir_abspath(self) -> Path:
        if self.output_abspath().is_dir():
            return self.output_abspath()
        else:
            return self.output_abspath().parent

    def output_filename(self) -> t.Optional[str]:
        if self.output_abspath().is_dir():
            return None
        else:
            return self.output_abspath().name
```

As I understand it, the intention is to take a path and decide if it refers to a subdirectory or a file; however, neither may yet exist since the build hasn't been run. Your suggestion was to look for an extension -- a name of `foo.pdf`, for example, is clearly a file. I'm dubious -- it could also be `foo.backup` (a directory) for someone experimenting.

Oscar's suggestion was that the output filename should come solely from the xml:id of the root element -- this seems like a better strategy to me. The path prefixed to this output filename would still come from the `output` element in `project.ptx`.

**Comment by bjones1** [comment]
> * For some reason, that code creates `assets` and `generated-assets` directories in the `output` directory.

Per today's conversation, @StevenClontz will track this down.

**Comment by oscarlevin** [comment]
Is this fixed @StevenClontz ?

**Comment by StevenClontz** [comment]
No, I should look into it. It's in my queue.

**Comment by StevenClontz** [comment]
That said, I don't think it's a blocker for 2.0.0, and can be folded into a bugfix release if needed.

**Comment by StevenClontz** [comment]
> * For some reason, that code creates `assets` and `generated-assets` directories in the `output` directory.

This is not a bug. I'm using a publication file that specifies `../assets` and `../generated-assets`, so when I point to a source file in `output/slides` of course it wants those directories there, even if I skip generation.

Maybe for custom builds there's no directory management, so creating these directories can be skipped. But for now it's harmless (and technically working as intended), so I'm closing.
