### ISSUE TITLE
codespaces should install latest pretext via pip

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#488]
Right now using the codespace template gives authors 1.6.0. We should always `pip install -r requirements.txt` to ensure the version of pretext we're using is the latest.

**Comment by bjones1** [comment]
I assume the current install is happening at https://github.com/oscarlevin/pretext-docker/blob/main/lite/Dockerfile#L6?

Do you suggest re-installing this by adding a `postCreateCommand.sh` to the current pretext-codespace? Another alternative is to rebuild the Docker container @oscarlevin maintains on every CLI release.

**Comment by oscarlevin** [comment]
Right now I have the dockerfile set up to rebuild each week.  I can look into adding a trigger for the action that rebuilds whenever a new pretext is deployed as well. 

I like the idea of having the docker image being where pretext is installed, rather than adding this to the devcontainer.json file, as it should speed things up.  But let me know why this is bad if you disagree.

**Comment by StevenClontz** [comment]
Having pretext installed in the docker image is fine as long as it's kept up-to-date.
