### ISSUE TITLE
Update calls to pretext.core to include pub_file argument

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#57]
For images and webwork, the pretext.core script now has a separate argument for a pub_file, which we need to respect.  I'll put pub_file=None in the right place, since we already add our pub_file to our params dictionary earlier on.  

I've got this done for images (on next commit) just need to sort out the various arguments for WeBWorK.  @rbeezer or @daverosoff, any guidance on the arguments from webwork_to_xml?

**Comment by daverosoff** [comment]
I think for now it's safe to do the same thing with the `webwork` function.

**Comment by rbeezer** [comment]
> any guidance on the arguments from webwork_to_xml

Should definitely pass in the `pub_file` since some adjustments via options from publisher may have an impact.

`abort_early` - a compromise for if certain errors are fatal or not.

`server_params` - necessary to connect to the same server for problem generation as will be used by readers when problems are rendered

**Comment by oscarlevin** [comment]
Thanks both of you.  Resolved at 59bd1fc.
