### ISSUE TITLE
Improve config file

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#59]
Next steps to make the project configuration file better:

- Namespace variables to avoid collision
- Split out individual stringparams as separate entries, to allow a user to modify them individually.
- On -v or -vv, display the config file's contents, or better yet, only the parts that are going to be used.

**Comment by StevenClontz** [comment]
Notes from #11:

> - User can specify the name of the config file (default is .ptxconfig) or write --config None to not use any config file. This allows for saving multiple configurations, or using standard defaults.
> - User specified options are only saved to config file with the -sc/--save-config flag set. When it is, the config file is also printed to the terminal.
> - Under the hood, the --config and --save-config click.options are now specified at the start of cli.py and called in the two functions that use them. The utils.write_config() function also includes some output to the terminal.

One day I'd like to have a canonical file that designates a PreTeXt[-CLI] project, like a `.git` folder is for Git repos. I think `.ptxconfig` is a reasonable name for this, and it should include this kind of info that tells CLI how the rest of the project is configured. But letting folks change the name would break things for this purpose. No problem at the moment, but something to consider eventually. (We could let folks save several configs within the file. I also prefer that the file be XML like the rest of PreTeXt, but at that point we're developing our own thing rather than relying on the nice library you found.)

I think `None` is the only use of capitalization in the CLI so far. I'd prefer `none`, but either way it shouldn't be case-sensitive. (I think I'm okay with not supporting a config file called `None`, but maybe `--no-config` is better?)

Once I've actually used this update a bit I may chime in more; we're good for 0.1 I think though.

**Comment by StevenClontz** [comment]
As I juggle several different PTX projects using the CLI, I find myself increasingly annoyed at the silent and automatic behavior of how we're saving custom defaults. Every project is ending up with different defaults, and there's no good way to manage them exposed in our CLI.

I also strongly believe that the default should be to only use saved defaults when asked to explicitly. Any documentation/guides that we put out on how to use the CLI will be broken for a user that has unwittingly saved some custom defaults that cause different behavior than the true default. So maybe the `--config/-c` flag should be required to use any options saved to the config file, and otherwise only the true defaults that appear with `--help` are used.

**Comment by StevenClontz** [comment]
I opened https://github.com/phha/click_config_file/issues/26 because I don't think there's actually a way to use that library where the user must explicitly ask to use their custom defaults but doesn't need to supply the path to the file containing them. In particular, it seems `--config` must be supplied a `FILE` when used.

**Comment by oscarlevin** [comment]
This is resolved by the creation of the project.ptx manifest
