### ISSUE TITLE
Allow `<executables>` in manifest v2

### ISSUE THREAD

**Issue by siefkenj** [PreTeXtBook/pretext-cli#693]
It seems that manifest `v2` removes the `<executables />` element and creates another magic file `executables.ptx` which is automatically under `.gitignore`.

While I understand the explanation given in the _Guide_ for this change, it is inconvenient and could lead to confusion for authors. Especially for solo-authored projects.
 1. If one sets up a project, pushes to github, the clones to another directory, they expect everything to be there for a reproducible build. But `executables.ptx` is `.gitignore`d by default, so the build may fail.
 2. Hopefully magic files can be kept to a minimum. Having a single `project.ptx` that has links to all other relevant files is fine. Having several magic files that get automatically read by `pretext-cli` sets up for confusion later.

My proposal: add back support for `<executables />` in `project.ptx`, and if you feel compelled, add a warning like

```
Warning: Including `<executables />` in your `project.ptx` may 
lead to builds failing on other systems or other environments 
configured differently. Consider using an `executables.ptx` file. See: ...
```

**Comment by StevenClontz** [comment]
On the contrary, I think you pointed out yourself the main issue of having executables in the project.ptx file (causing potential build failures on other machines), which is why it's factored out to another file and gitignored. I don't want to encourage PreTeXt projects that *only* build on a single person's machine*; if you want to risk that, then you can overcome the slight friction you've described here.

* I dream of a world where deployments generally happen in the cloud via GitHub Actions or similar. Which means encouraging authors to write "clean" PreTeXt that works on a fresh Docker image.

**Comment by oscarlevin** [comment]
It seems like either direction is a compromise between competing principles.  On the one hand, we should make it possible for a project to be built on two different systems (I use three or four different setups for my book: windows, wsl, ubuntu at home, and codespaces).  On the other hand, its nice not to have a separate configuration file.

But with two files, it is possible for an author to remove the `executables.ptx` from their `.gitignore`.  With everything in one file, it is not possible to have that part of the configuration ignored.  So I'm with @StevenClontz here that it is more flexible to keep them separate.  

Also keep in mind that for most authors, there is no need to have an executables file at all, since the defaults should work most of the time, and definitely do with codespaces.

**Comment by siefkenj** [comment]
I'm a bit confused. I would imagine the behavior being that if there is no `<executables>` in `project.ptx`, then the external file is referenced. No incompatibility is introduced by allowing that...we can have it both ways!

**Comment by StevenClontz** [comment]
I still push back on this: author sets an executable in project.ptx, it's checked into version control, and then the book only works on their machine. I really want version controlled files to be machine-agnostic as much as possible.

**Comment by siefkenj** [comment]
At some point, you've got to trust your users. If they are setting `<executables>` at all, they are not in codespaces, and so are by definition "advanced" users.

This is also not a theoretical issue. I filed this issue because I had to figure out how all this worked and it took me way more time than it should have. It was very frustrating.

Like I've said, I think it is fine if `pretext` gives warnings when someone creates "non-portable" configurations. An advanced user can evaluate and ignore warnings, and it will steer non-advanced users to do what you suggest.

In terms of future adoption, I suggest that the CLI add an additional principle, which is `strive to provide an environment that a person familiar with software development practices will not be surprised by`. I assert that a typical user would expect _only_ cache/output/tmp files to be included in `.gitignore` by default. Configuration files, especially ones that don't start with a `.` should not be automatically added to `.gitignore`. I suggest at least one of the following:
 1. Don't `.gitignore` `executables.ptx` by default.
 2. Change the name to `.executables.ptx` or `.local_config/executables.ptx`

Separate from those suggestions, if you still intend to forbid an `<executables>` tag, I suggest at a minimum you add add to the error message and say something like, 
```
`<executables>` must be specified in an external file `executables.ptx`,
not in your `project.ptx` file. See ... for a guide or run 
`pretext generate config executables` to create an 
`executables.ptx` file populated with the default values.
```
