### ISSUE TITLE
tmp folders not getting removed (again)

### ISSUE THREAD

**Issue by bnmnetp** [PreTeXtBook/pretext-cli#838]
My root partition got filled up again because there are tons of folders called `ptx-xxsjdflsj` in my /tmp folder. These are all new, so it seems like someone is not cleaning up after themselves.

**Comment by oscarlevin** [comment]
The `ptx-` prefix is created by core routines; cli routines create a `pretext_` prefix (to *obviously* distinguish between them..)

I don't think it is all core created temp folders though.  I can go looking in pretext/pretext, but is there any chance that you could check if there is any particular type of content inside of them?  Also, in the build logs, is there the line ""Unable to release temporary directories.  Please report this error to pretext-support" (which might start with "error: ")?

**Comment by oscarlevin** [comment]
Yet, I think it is probably an issue with the CLI not calling the release_temporary_directories, since I'm not seeing those info messages.

**Comment by oscarlevin** [comment]
Alright, this will be fixed in 2.7.1 to be released momentarily.  

I'm scratching my head how this could have been missed.  Is it possible that this issue dates back to when you upgraded to CLI v2?  It seems like we have only been cleaning temporary generate directories, not build directories, since then!
